### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ottovisa** [areee/MusicMachine#1]
**Projekti ladattu:** 2.2.2015 klo 11:59

**Yleisesti:** Projektin aihe on mielenkiintoinen ja hyvin keksitty. Itselläni ei ole vielä kauheasti kokemusta Javasta saatika muistakaan ohjelmointikielistä, joten yllätyin positiivisesti siitä että Javalla pystyy tekemään tällaisenkin ohjelman. Projekti näyttää olevan ihan hyvällä mallilla ja näyttäisi siltä, että tiedät mitä olet tekemässä!

**Positiivista:**
- Luokkien jako paketteihin on selkeä
- Hyvin nimetyt metodit ja muuttujat
- Single responsibility principle näyttäisi toteutuvan
- Tekstikäyttöliittymä on helppokäyttöinen ja graafisen käyttöliittymän suunnitelma näyttäisi alustavasti hyvältä

**Parannettavaa/ehdotuksia:**
- Tarvitseeko lukija välttämättä oman luokan, jos siltä kysytään vain komentoa?
- Testit eivät näytä vielä kovin kattavilta. Toki luokilla on paljon gettereitä ja settereitä, sekä testit testaavat myös käyttöliittymät, jonka vuoksi prosentit ovat alhaisia, sillä näitähän ei tarvitse testata. Voisihan pitin konfiguroida niin, että se testaisi vain logiikan?

**Comment by areee** [comment]
Kiitos katselmointipalautteesta!
