### ISSUE TITLE
Koodikatselmointi 24.2 23:59

### ISSUE THREAD

**Issue by klaevv** [areee/MusicMachine#2]
Kryptinen plugin-virhe esti projektin buildaamisen, en ole varma missä vika piilee, tosin yhden importin huomasin osoittavan väärään paikkaan. Koodi on siistiä, clean code periaatetta mukailevaa. Dokumentaatio on myös kattavaa ja hyvin kirjoitettua. Ohjelman käyttöliittymä vaikuttaa hyvin suunnitellulta, valitettavasti sen testaaminen ei em. bugin takia onnistunut.

**Comment by areee** [comment]
Kiitos koodikatselmoinnin palautteesta! Joo, ValitseKayttoliittyma-luokkaan oli refaktoroinnista huolimatta eksynyt virheellinen import, jonka havaitsin jo eilisessä demo-tilaisuudessa, mutten ehtinyt sitä korjata omalle koneelleni. Korjaan sen nyt, toivon mukaan ohjelma toimii sen jälkeen muillakin koneilla kuin omallani.
